// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gensql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID          int64
	UserID      int64
	Amount      pgtype.Numeric
	Description string
	Category    string
	Date        pgtype.Timestamptz
	Type        string
	Currency    string
	Status      string
	Account     string
	Tags        []string
	Notes       *string
	HasReceipt  bool
	ReceiptUrl  *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	Name         *string
	AvatarUrl    *string
	Preferences  []byte
}
