// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (user_id, amount, description, category, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, amount, description, category, date
`

type CreateTransactionParams struct {
	UserID      int64
	Amount      pgtype.Numeric
	Description string
	Category    string
	Date        pgtype.Timestamptz
}

// internal/database/queries/transactions.sql
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.Category,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Category,
		&i.Date,
	)
	return i, err
}

const getTotalSpending = `-- name: GetTotalSpending :one
SELECT COALESCE(SUM(amount), 0)::numeric
FROM transactions
WHERE user_id = $1
`

func (q *Queries) GetTotalSpending(ctx context.Context, userID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalSpending, userID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, amount, description, category, date FROM transactions
WHERE user_id = $1
ORDER BY date DESC
LIMIT 100
`

func (q *Queries) ListTransactions(ctx context.Context, userID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.Category,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
